# Generated by Django 5.1.2 on 2024-10-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(default="Anonymous", max_length=200),
        ),
    ]
